Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
pip install numpy 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 3.1 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

# Creating Arrays using Numpy

arr1 = np.array([1,2,3,4,5])  # 1D Array
print(arr1)
print(type(arr1))
print(arr1.shape)   # gives the dimensions of the array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
# 2D Arrays

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)  # (2,5) -> 2 rows and 5 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Size (number of elements):", arr.size)  # Output: 6
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Size (number of elements): 6
Shape: (2, 3)
Number of dimensions: 2
Data type: int64
Item size (in bytes): 8


In [11]:
# NUMPY VECTORISED OPERATIONS

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Add:" , arr1+arr2)

# Element-wise Substraction
print("Sub:" , arr1-arr2)

# Element-wise Multiplication
print("Multiply:" , arr1*arr2)

# Element-wise Division
print("Divide:" , arr1/arr2)

Add: [11 22 33 44 55]
Sub: [ -9 -18 -27 -36 -45]
Multiply: [ 10  40  90 160 250]
Divide: [0.1 0.1 0.1 0.1 0.1]
